insert into Users (Name, Password) values ('FoxMulder', '203B70B5AE883932161BBD0BDED9357E763E63AFCE98B16230BE33F0B94C2CC5')
insert into ProjectGroups(Name) values ('Customers')
insert into Projects(GroupId, Name) values (1, 'NSA')
insert into Projects(GroupId, Name) values (1, 'FBI')
insert into Projects(GroupId, Name) values (1, 'Illuminati')
insert into ProjectGroups(Name) values ('Products')
insert into Projects(GroupId, Name) values (2, 'FNORD Organizer')
insert into Projects(GroupId, Name) values (2, 'MKULTRA Addressbook')
insert into ProjectGroups(Name) values ('Features')
insert into Projects(GroupId, Name) values (3, 'fancy stuff')
insert into Projects(GroupId, Name) values (3, 'self destruction')
insert into Tasks(Name, Productive, ProjectGroupId) values ('Local Support', 0, null)
insert into Tasks(Name, Productive, ProjectGroupId) values ('Support', 1, 1)
insert into Tasks(Name, Productive, ProjectGroupId) values ('Bugfixing', 0, 2)
insert into Tasks(Name, Productive, ProjectGroupId) values ('Customization', 1, 1)
insert into Tasks(Name, Productive, ProjectGroupId) values ('Documentation', 0, 2)
insert into Tasks(Name, Productive, ProjectGroupId) values ('Development', 1, 3)
insert into Tasks(Name, Productive, ProjectGroupId) values ('Meeting', 0, null)